trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterVersion: '3.19.0'  # Change to your desired Flutter version

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    echo "##vso[task.prependpath]$(Build.SourcesDirectory)/flutter/bin"
    flutter doctor
  displayName: 'Install Flutter'

- script: |
    flutter pub get
  displayName: 'Install dependencies'

- script: |
    flutter build apk --release
  displayName: 'Build APK'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/app/outputs/flutter-apk/app-release.apk'
    ArtifactName: 'apk'
    publishLocation: 'Container'
