trigger:
  - main  # or your branch name

pool:
  vmImage: 'macos-latest'  # Required for iOS builds

variables:
  buildDirAndroid: 'build/app/outputs/flutter-apk'
  buildDirIOS: 'build/ios/iphoneos'

steps:
- task: UseFlutterVersion@0
  inputs:
    version: '3.19.0'  # Replace with your Flutter version

- script: flutter pub get
  displayName: 'Install dependencies'

- script: flutter build apk --release
  displayName: 'Build APK'

- script: flutter build ios --release --no-codesign
  displayName: 'Build IPA (no code signing)'

- task: CopyFiles@2
  inputs:
    contents: '$(buildDirAndroid)/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)/apk'

- task: CopyFiles@2
  inputs:
    contents: '$(buildDirIOS)/*.app'
    targetFolder: '$(Build.ArtifactStagingDirectory)/ios'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'flutter-build'
    publishLocation: 'Container'
