- script: |
    flutter --version
    flutter pub get
    flutter clean
    flutter build apk --debug
    echo "Debug APK generated at: build/app/outputs/flutter-apk/app-debug.apk"
  displayName: 'Build Debug APK'
