trigger:
  branches:
    include:
      - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  sdkVersion: '30'
  buildToolsVersion: '30.0.3'

steps:
- task: UseJava@1
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'

- task: AndroidToolInstaller@1
  inputs:
    version: 'latest'

- script: |
    echo "y" | sdkmanager "platforms;android-$(sdkVersion)" "build-tools;$(buildToolsVersion)"
  displayName: 'Install Android SDK components'

- script: ./gradlew assembleDebug
  displayName: 'Build APK'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'app/build/outputs/apk/debug'
    ArtifactName: 'apk'
    publishLocation: 'Container'
