name: Build and Deploy Flutter Apps

on:
  push:
    branches:
      - master  # Adjust to 'master' if your repo uses it

jobs:
  build:
    name: Build APK and IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Install pub dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa
          retention-days: 7

  deploy:
    name: Deploy to OpenShift ROSA
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin

      - name: Login to OpenShift
        run: oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}

      - name: Deploy Android APK
        run: |
          oc new-app --name=android-app --docker-image=quay.io/your-repo/android-app:latest
          oc start-build android-app --from-file=build/app/outputs/flutter-apk/app-release.apk --follow

      - name: Deploy iOS IPA
        run: |
          oc new-app --name=ios-app --docker-image=quay.io/your-repo/ios-app:latest
          oc start-build ios-app --from-file=build/ios/iphoneos/app.ipa --follow
